### PR TITLE
Slightly faster relative_path_from (91.2% -> 93.4%)

### PR DESCRIPTION
**Pull request by glebm**
Locally: 88.7% -> 90.7%
Travis: [91.2%](https://travis-ci.org/danielpclark/faster_path/jobs/353111981) -> [93.4%](https://travis-ci.org/danielpclark/faster_path/jobs/353119848#L1020)

### CODE REVIEW

**Comment by danielpclark** [comment]
Hey @glebm , I'd like to add you to this project.  Are you interested?  We can review each others work.

**Comment by glebm** [comment]
I don't know if that's necessary as I only contribute occasionally but I don't mind

**Comment by danielpclark** [comment]
I didn't mean to burden you with any unwanted responsibility.  I just wanted you to know I'm honored to work with you on this and I value your input.

**Comment by glebm** [comment]
Thanks!

**Pull request merged**
