### PR TITLE
Add rust version of directory method

### PR DESCRIPTION
**Pull request by mrageh**

### CODE REVIEW

**Comment by danielpclark** [comment]
Excellent @mrageh Can you add some tests to verify the behavior is the same as the built in method in weird situations?  Like the A, B, C tests in the chop_basename test.  Also we've just switched away from includes to modules `mod`.  So if you could change that I'll verify this and merge it! :+1:

**Comment by gogainda** [comment]
@mrageh you can borrow from there test cases

**Comment by mrageh** [comment]
@danielpclark I've added the tests and moved over to use `pub mod` to include the method.

**Comment by danielpclark** [comment]
Awesome!  I think you're underselling the improvement.  On my Netbook I'm seeing 36% performance increase.  Would you like to change the number to this in the README?

```
bench_rust_directory?	 0.173023	 0.170350	 0.175760	 0.181842	 0.169162
 PASS (1.03s) :: bench_rust_directory?
bench_ruby_directory?	 0.277740	 0.272405	 0.285280	 0.272360	 0.272193
 PASS (1.54s) :: bench_ruby_directory?
```

**Comment by mrageh** [comment]
Wow that's a huge improvement on your machine, on my mac the stats are different;

```
bench_rust_directory?    0.158879        0.158444        0.155209        0.156522        0.161104
 PASS (0.82s) :: bench_rust_directory?
bench_ruby_directory?    0.203498        0.209988        0.203260        0.201285        0.205856
 PASS (1.05s) :: bench_ruby_directory?
```

The way I calculated the performance was `((1.05 - 0.82) / 1.05) * 100`

**Comment by danielpclark** [comment]
Yeah.  My netbook is slow and I haven't been running any other numbers on it.  But since it's a slower machine I guess Rust is just that much faster.

**Comment by danielpclark** [comment]
Great job on this btw!

**Comment by mrageh** [comment]
Thanks this is the first time I've done something useful in Rust

**Pull request merged**
