### PR TITLE
Replace handrolled build system with Thermite

### LINKED ISSUE #34: Pre-built binaries to remove the `rustc` dependency?
Have you considered uploading pre-built binaries so that users don't need rustc installed? I would be willing to contribute a patch.

### PR DESCRIPTION
**Pull request by malept**
## Summary

Use [thermite](https://github.com/malept/thermite) to help build and distribute faster_path.

This has several advantages to the current system:
- Build errors are shown (#71)
- Has a mode to install a Rust binary from GitHub releases when `cargo` is not found on the installing system (#34)
- Thermite has been tested cross-platform (via an [example project](https://github.com/malept/rusty_blank))

Fixes #34, #71.
## Next Steps

In order to use the GitHub releases feature of Thermite, I would suggest adding a [GitHub releases deploy section to your Travis CI config](https://docs.travis-ci.com/user/deployment/releases). I have an example of this in my [`rusty_blank` repository](https://github.com/malept/rusty_blank/blob/1cb02eb36ec15e38a74e4e38b10ca904f812259e/.travis.yml#L51-L61). That repository also has an [AppVeyor CI config](https://github.com/malept/rusty_blank/blob/1cb02eb36ec15e38a74e4e38b10ca904f812259e/.appveyor.yml) so that I can create binaries for Windows. (Although perhaps it might not be necessary - I haven't researched how feasible it is to cross-compile Rust extensions for Windows via Travis CI.)

If you want, I can add the deploy section (sans deploy key, obviously) to the Travis CI config.

### CODE REVIEW

**Comment by danielpclark** [comment]
I've opened [an issue](https://github.com/malept/thermite/issues/1) for verifying thermite works with tests and to help make sure it won't become broken in the future.

**Comment by malept** [comment]
For the record, this pull request should be good to go. Let me know if there's anything that needs to be changed or requires further discussion.

**Comment by danielpclark** [comment]
Could you educate on me on how the binary build and the hosting of binaries for each architecture is achieved?  I guess I get the concept but haven't fully grokked the how.

* Where are the binaries built?
* Where are they stored?
* How are they trusted?

I see it has an option for Github binary releases.

* Does this put the binaries in the origin/master branch of the Github repo?
* Could I keep the binaries separate for the sanity of downloading from git source?

**Comment by malept** [comment]
> Where are the binaries built?

Via your CI service(s). For me, Travis (Linux/OSX) and AppVeyor (Windows).

> Where are they stored?

The way I've written this pull request, GitHub Releases, in your case https://github.com/danielpclark/faster_path/releases. In theory you could instead deploy to someplace like bintray or S3.

> How are they trusted?

Trust with CI is Hard:tm:. I do have an [issue open](https://github.com/malept/thermite/issues/14) and some code partway written to add support for checksums, but that's only a part of the way when you're dealing with Trust.

> Does this put the binaries in the origin/master branch of the Github repo?
> Could I keep the binaries separate for the sanity of downloading from git source?

Thermite does **not** commit Rust binaries into a git repository. I personally don't put binaries anywhere near my git repositories unless I have to (and even then, I would evaluate git-lfs first).

**Comment by stereobooster** [comment]
Any news on that? Do you need help?

**Comment by danielpclark** [comment]
I'm ready to move forward with this @stereobooster & @malept .  I've posted a question about cross compilation here: https://github.com/malept/thermite/issues/32

**Comment by malept** [comment]
I will be happy to rebase this PR.

@danielpclark Are checksum and/or cross compilation support the only blockers?

**Comment by danielpclark** [comment]
Yes I believe so.  But I'm cool with getting this going now as is and we can build on it.

**Comment by danielpclark** [comment]
I have written a just-in-case bit of code that would help people who gem installed and didn't get the compiled asset: https://github.com/danielpclark/faster_path/blob/master/lib/faster_path/asset_resolution.rb

You may need to update this to point to any changes in location of the built library.

**Comment by malept** [comment]
That...is a lot of nesting. I'll try to find some time to adapt that.

**Comment by danielpclark** [comment]
> That...is a lot of nesting.

Haha!  You're welcome to refactor it.  It's really just a file check and then two paths for whether Rust is available or not.

**Comment by danielpclark** [comment]
If you find the time to get this done soon (say maybe this weekend) I'd love to contribute to Thermite as well to help with cross compilation.  My mind is gearing up for it as I've been thinking heavily in this area.

**Comment by malept** [comment]
It might happen Sunday, we'll see. I would be happy to have help with the cross compilation feature.

**Comment by danielpclark** [comment]
I believe my asset resolution code may have caused problems, this PR included.  After I write the next two methods for this library I'll take the work you've done here in this PR and apply it to FasterPath.

If I have any questions that come up are you online enough that I might be able to get answers @malept ?

**Comment by malept** [comment]
Less so in the next couple of days, but after that I should be able to answer questions (or at least say that I'd need to do research) at a reasonable pace.

**Comment by danielpclark** [comment]
Moved to #141.  Working on the Github releases part now.

**Pull request closed without merging**
